In [1]:
import numpy as np
filename = '/Volumes/Extreme_SSD/mvts_transformer_robot/experiments_user_set_size/haptic_10_users/haptic_10_users_user1_legitimate/test_results.npz'
data = np.load(filename, allow_pickle=True)
lst = data.files
print(lst)

['target_masks', 'targets', 'predictions', 'metrics', 'IDs']


In [2]:
import torch
import numpy as np
predictions = torch.from_numpy(np.concatenate(data['predictions'], axis=0))
probs = torch.nn.functional.softmax(predictions)  # (total_samples, num_classes) est. prob. for each class and sample
predictions = torch.argmax(probs, dim=1).cpu().numpy()  # (total_samples,) int class index for each sample
probs = probs.cpu().numpy()

/Users/huanglong/opt/anaconda3/envs/deepLearning/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/var/folders/rr/c6bzrfyd5tv0pt24ky9_l4d40000gn/T/ipykernel_25485/923225844.py:4: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  probs = torch.nn.functional.softmax(predictions)  # (total_samples, num_classes) est. prob. for each class and sample


In [6]:
print(probs)

[[9.5864010e-01 4.1359868e-02]
 [2.1920123e-03 9.9780804e-01]
 [2.7451737e-05 9.9997258e-01]
 ...
 [1.0000000e+00 3.5367654e-18]
 [1.0000000e+00 1.9420524e-16]
 [1.0000000e+00 1.1291952e-16]]


In [7]:
print(predictions)

[0 1 1 ... 0 0 0]


In [8]:
targets = torch.from_numpy(np.concatenate(data['targets'], axis=0))
targets = targets.cpu().numpy()
print(targets)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [9]:
from scipy import io
io.savemat('predictions.mat', {"predictions": predictions })
io.savemat('targets.mat', {"targets": targets })